CREATE DATABASE IF NOT EXISTS INV_TELMEX;

USE INV_TELMEX;

#TABLA USUARIO
CREATE TABLE IF NOT EXISTS USUARIOS
(
	ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
	NOMBRE_USUARIO VARCHAR(100) UNIQUE,
	PASSWORD_USUARIO VARCHAR(200) NOT NULL,
	PERMISOS_USUARIO VARCHAR(200),
	STATUS ENUM('ACTIVO','NO ACTIVO') NOT NULL
);

INSERT INTO USUARIOS VALUES('0','ADMIN',MD5('0112'),NULL,'ACTIVO');

#TABLA EMPLEADOS
CREATE TABLE IF NOT EXISTS EMPLEADOS
(
	ID_EMPLEADO INT AUTO_INCREMENT PRIMARY KEY,
	NOMBRE_EMPLEADO VARCHAR(100) NOT NULL,
	AP_PATERNO_EMPLEADO VARCHAR(100) NOT NULL,
	AP_MATERNO_EMPLEADO VARCHAR(100),
	PUESTO VARCHAR(100),
	STATUS ENUM('ACTIVO','NO ACTIVO')
);

#TABLA MATERIALES
CREATE TABLE IF NOT EXISTS MATERIALES
(
	CODIGO INT NOT NULL PRIMARY KEY,
	DESCRIPCION VARCHAR(100) NOT NULL,
	UNIDAD_DE_MEDIDA VARCHAR(10),
	EXISTENCIA FLOAT(6,2),
	LIMITE_INFERIOR FLOAT(6,2),
	STATUS ENUM('ACTIVO','NO ACTIVO')
);

#TABLA VALES
CREATE TABLE IF NOT EXISTS VALES
(
	ID_VALE INT AUTO_INCREMENT PRIMARY KEY,
	FECHA DATE NOT NULL,
	HORA TIME NOT NULL,
	ID_USUARIO INT NOT NULL,
	ID_EMPLEADO INT NOT NULL,
	STATUS_VALE ENUM('SURTIDO','CANCELADO'),
	MOTIVO_CANCELACION VARCHAR(200),

	FOREIGN KEY(ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
	FOREIGN KEY(ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO)
);

#TABLA-RELACION VALES-MATERIALES

CREATE TABLE IF NOT EXISTS VALES_MATERIALES
(
	ID_MOVIMIENTO INT AUTO_INCREMENT PRIMARY KEY,	
	ID_VALE INT NOT NULL,
	CODIGO INT NOT NULL,
	CANTIDAD INT NOT NULL,

	FOREIGN KEY(ID_VALE) REFERENCES VALES(ID_VALE),
	FOREIGN KEY(CODIGO) REFERENCES MATERIALES(CODIGO)
);

#TABLA MOVIMIENTOS INVENTARIO

CREATE TABLE IF NOT EXISTS MOVIMIENTOS
(
	ID_MOVIMIENTO INT AUTO_INCREMENT PRIMARY KEY,
	FECHA DATE NOT NULL,
	HORA TIME NOT NULL,	
	ID_USUARIO INT NOT NULL,
	TIPO_MOVIMIENTO ENUM('MANUAL','VALE'),
	ID_VALE INT,
	CODIGO INT NOT NULL,
	ENTRADA FLOAT(6,2),
	SALIDA FLOAT(6,2),
	EXISTENCIA_INICIAL FLOAT(6,2),
	EXISTENCIA_FINAL FLOAT(6,2),
	COMENTARIOS TEXT,


	FOREIGN KEY(ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
	FOREIGN KEY(ID_VALE) REFERENCES VALES(ID_VALE),
	FOREIGN KEY(CODIGO) REFERENCES MATERIALES(CODIGO)
);